services:
  strapiDB:
    container_name: strapiDB
    image: postgres:12.0-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - strapi_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - strapi_data:/var/lib/postgresql/data

volumes:
  strapi_data:

networks:
  strapi_network:
    name: strapi
    driver: bridge
